import = ["~/dotfiles/extern/catppuccin/alacritty/catppuccin-macchiato.toml"]
live_config_reload = true
ipc_socket = false

[window]
padding = { x = 3, y = 3 }
decorations = "None"
opacity = 0.9
decorations_theme_variant = "Dark"

[scrolling]
history = 100000

[font]
normal = { family = "RobotoMono Nerd Font Mono", style = "Regular" }
size = 9.0

[colors]
cursor = { text = "#000000", cursor = "#ffffff" }
