[general]
import = ["~/dotfiles/extern/catppuccin/alacritty/catppuccin-macchiato.toml"]
live_config_reload = true
ipc_socket = false

[window]
padding = { x = 3, y = 3 }
decorations = "None"
opacity = 0.9
decorations_theme_variant = "Dark"

[scrolling]
history = 100000

[font]
normal = { family = "RobotoMono Nerd Font Mono", style = "Regular" }
size = 9.0

[colors]
cursor = { text = "#000000", cursor = "#ffffff" }

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t/&*@%;#"

[keyboard]
bindings = [
    { mods = "Control", key = "à", action = "ResetFontSize" },
    { mods = "Control|Alt", key = "n", action = "SpawnNewInstance" },
    { mods = "Shift", key = "/", mode = "Vi", action = "SearchBackward" },
    { mods = "Shift", key = "?", mode = "Vi", action = "SearchForward" },
    { mods= "Control", key = "o", mode = "Vi", action = "Open" },

    # Neovim: harpoon keybindings
    { mods = "Alt", key = "é", chars = "\u001b[1;5P" },  # Control+F1
    { mods = "Alt", key = "è", chars = "\u001b[1;5Q" },  # Control+F2
    { mods = "Alt", key = "ç", chars = "\u001b[1;5R" },  # Control+F3
    { mods = "Alt", key = "à", chars = "\u001b[1;5S" },  # Control+F4
]
