# https://wiki.hypr.land/Configuring/Gestures/

gestures {
    # workspace_swipe = true
    # workspace_swipe_fingers = 3
    workspace_swipe_create_new = true
    workspace_swipe_direction_lock = true
    workspace_swipe_forever = false
    workspace_swipe_use_r = true
}

gesture = 3, horizontal, workspace
gesture = 4, horizontal, special, magic
gesture = 4, up, fullscreen
gesture = 4, down, fullscreen, maximize
