[manager]
show_hidden = true

[opener]
play = [
    { run = 'vlc "$@"', orphan = true },
]
vlc = [
    { run = 'vlc "$@"', orphan = true },
]
amberol = [
    { run = 'amberol "$@"', orphan = true },
]

[open]
prepend_rules = [
    { mime = "inode/directory", use = ["edit", "open", "vlc", "reveal"] },
    { mime = "audio/*", use = ["amberol", "vlc", "reveal"] },
]
