#!/usr/bin/sh

if [ -f "${HOME}/.profile" ]; then
    . "${HOME}/.profile"
fi

USER_RESOURCES="${XDG_CONFIG_HOME}/xresources"
SYS_RESOURCES="/etc/X11/xinit/.Xresources"

if [ -f "$SYS_RESOURCES" ]; then
    xrdb -merge "$SYS_RESOURCES"
fi
if [ -f "$USER_RESOURCES" ]; then
    xrdb -merge "$USER_RESOURCES"
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

exec dbus-run-session i3
